### PR TITLE
Bump three types to 153

### PR DESCRIPTION
**Pull request by marwie**
see PR https://github.com/pixiv/three-vrm/issues/1251

### CODE REVIEW

**Comment by 0b5vr** [comment]
Didn't noticed @types/three for r153 has been released, thank you.
I will check this later.

**Comment by marwie** [comment]
No problem, types for 154 are already released too - not sure if you tested the package with latest three yet

When the types errors are fixed we could start using it in our engine which uses three 154

**Comment by 0b5vr** [comment]
@marwie 

I will bump to r154 along with the type definition later, I'm not sure whether the library works as is or not.

I'm going to deploy the @types/three r153 changes for now.

Could you also apply the change to `yarn.lock`?

**Comment by marwie** [comment]
@0b5vr done

**Comment by 0b5vr** [comment]
Thank you!

**Review by 0b5vr — APPROVED** [review]

**Comment by marwie** [comment]
@0b5vr let me know if/when I should test with 154. Ideally we can update the types to 154 as well to avoid the peer dependency errors altogether :)

image

**Comment by 0b5vr** [comment]
Yes, we definitely need to reconsider peerDependencies to change to a realistic way.

**Pull request merged**
